### ISSUE TITLE
Problem in surface resistance in SUEWS output file

### ISSUE THREAD

**Issue by ljarvi** [UMEP-dev/SUEWS#126]
When printing our surface resistance in the SUEWS output file, the model prints out ****** as the resistance values get too large. In the calculation of RS some limit for not getting too high values should be added.

**Comment by sunt05** [comment]
can use input data in #127 to reproduce this error.

**Comment by sunt05** [comment]
Hi @ljarvi ,

now as the software issue #127 has been resolved, I managed to run SUEWS with the snow module on and reproduce the high RS issue above.

As I can see here:
https://github.com/UMEP-dev/SUEWS/blob/c85f5a4e850e9e60737f8546cd8cdb9ebaef05d8/SUEWS-SourceCode/src/suews_phys_resist.f95#L345-L363

gs, i.e. 1/RS, is limited to a low value when the g_LAI part is controlled by snow fractions - I then found snow fractions are ~100% during most of simulation period - this is the apparent issue but should it be so?

Since I'm unfamiliar with the snow part, I'll leave this for your justification - once you have better idea, let's work on this further.

**Comment by sunt05** [comment]
## QE
![5b878bd3-49c0-4199-84ba-1206874651fd](https://user-images.githubusercontent.com/1802656/186654336-f27062ca-1cdf-4e89-b320-355e83fd8ed6.png)

## gs


---
input data file
[snow.zip](https://github.com/UMEP-dev/SUEWS/files/9424232/snow.zip)

**Comment by sunt05** [comment]
QE issue identified

when snow is gone, the overall QE is shut down - this issue is more apparent when zooming into April of 2019 of the above case.

- QE
![47bb79ff-c868-47bf-9315-ce79a3a56f37](https://user-images.githubusercontent.com/1802656/186655228-da617759-505d-40cc-a247-85f53b9227c7.png)

- gs 

![632ac68a-c122-4823-8ba2-819cfd63fb66](https://user-images.githubusercontent.com/1802656/186655284-3313aaf3-7465-4eb2-bb1b-a6e92901f32b.png)

- snow fractions

![f2d208b1-f6a9-48f6-b968-e0d91ee7ea82](https://user-images.githubusercontent.com/1802656/186655320-8b3e41b9-9418-45b2-9070-f8368b36b835.png)

**Comment by ljarvi** [comment]
With the newest master branch code the issue with printing ****** is Rs column remains. I suggest we modify the code that if gs<0.01 (not gs<0) will fix the issue.

**Comment by sunt05** [comment]
No longer an issue as this will now be handled on the Python side.
