### ISSUE TITLE
frfossilfuel_heat & frfossilfuel_nonheat

### ISSUE THREAD

**Issue by becqui00** [UMEP-dev/SUEWS#206]
I’m currently working with SUEWS/SuPy. I have a question about two df_state variables. 
I’m currently trying to model “FcBuild” for a specific site. For that I need among other things the variables “frfossilfuel_heat” and “frfossilfuel_nonheat”. Now I tried to calculate my FcBuild with the standard value of the two variable which is 0.7 for each. The result for FcBuild was much too high (I used EmissionsMethod 45). 
My question is: don't the two variables have to add up to 1? So for example “frfossilfuel_heat” = 0.7 and “frfossilfuel_nonheat”= 0.3. If that’s not the case, maybe I have to change this variable “ef_umolco2perj”. I didn’t find any further informations about that topic in the documentation. Maybe you can help me out. 
 
Cheers, 
becqui00

**Comment by havum** [comment]
Hi, thanks for the question! 

CO2 emissions from buildings are derived from anthropogenic heat. Anthropogenic heat is divided into different parts: base and two temperature dependencies, heating or cooling.

These two fractions describe how much of this anthropogenic heat is produced by local fossil fuel emissions, 1) frfossilfuel_heat is the component directly related to how much of the building heating is produced by local fossil fuels compared to district heating, and 2) frfossilfuel_nonheat it the component related to other possible sources of CO2 from buildings that are not dependent on temperature but still produce anthropogenic heat. Therefore, they don't need to add up to 1. Depending on your heating source, you should modify the parameter ef_umolco2perj.

In the case of Helsinki, we have used the values frfossilfuel_heat = 0.05 and frfossilfuel_nonheat = 0, because a large part of our heating comes from district heating, and we don't expect any additional CO2 sources from, for example, cooking.

Best,
Minttu

**Comment by sunt05** [comment]
Hi @becqui00, please close this issue if Minttu's answer addressed your question. thanks!
